sudo: required
services:
  - docker

before_install:
  - docker build -t hudaipena/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hudaipena/react-test npm test

after_success:
    - docker build -t hudaipena/multi-client ./client
    - docker build -t hudaipena/multi-nginx ./nginx
    - docker build -t hudaipena/multi-server ./server
    - docker build -t hudaipena/multi-worker ./worker
    